server {
    listen 80;
    client_max_body_size 50M;

    # Frontend — painel de controle
    location / {
        proxy_pass         http://painel:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    # Backend FastAPI — remove o prefixo /api antes de repassar
    location /api/ {
        proxy_pass         http://backend:8000/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 120s;
    }

    # Proxy para o Bucket do MinIO
    location /app-jornada/ {
        proxy_pass         http://minio:9000/app-jornada/;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        client_max_body_size 50M;
    }
}
