server {
    listen 80;
    server_name rafael.arkana.fun;

    # Desafio do Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name rafael.arkana.fun;
    client_max_body_size 50M;

    ssl_certificate /etc/letsencrypt/live/rafael.arkana.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rafael.arkana.fun/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Rota para download direto do APK do motorista (versão genérica ou versionada ex: app-jornada-v1.0.4.apk)
    location ~* \.apk$ {
        root /usr/share/nginx/html;
        default_type application/vnd.android.package-archive;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        expires off;
    }

    # Frontend — painel de controle
    location / {
        proxy_pass         http://painel:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    # Backend FastAPI — remove o prefixo /api antes de repassar
    location /api/ {
        proxy_pass         http://backend:8000/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 120s;
    }

    # Proxy para o Bucket do MinIO
    location /app-jornada/ {
        proxy_pass         http://minio:9000/app-jornada/;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        client_max_body_size 50M;
    }

    # Proxy para o OSRM
    location /osrm/ {
        proxy_pass         http://osrm:5000/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
}
